#!/usr/bin/python3

import socket
import os
import sys

SOCK_ADDR = os.getenv('PYBLK_SOCK_ADDR', default='/tmp/pyblk.sock')
try:
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    sock.connect(SOCK_ADDR)
    sock.sendall('\0'.join(sys.argv[1:]).encode())
    buff = b''
    while True:
        tmp = sock.recv(1024)
        if not tmp:
            break
        buff = b''.join([buff, tmp])
    print(buff.decode('UTF-8'))
except socket.error as e:
    sys.stderr.write(f'Can\'t connect to {SOCK_ADDR}\n')
finally:
    sock.close()

