#!/usr/bin/python3

import os
import sys
import Server

SOCK_PATH = os.getenv('PYBLK_SOCK_ADDR', default='/tmp/pyblk.sock')
SHELL = os.getenv('PYBLK_SHELL', default='/bin/sh')

def main():
    try:
        server = Server.Server(SOCK_PATH, SHELL)
        server.loop()
    finally:
        server.close()
        sys.exit(0)


if __name__ == '__main__':
    main()
